[supabase]
host = "aws-0-us-west-1.pooler.supabase.com"
database = "postgres"
dbname = "postgres"
user = "postgres.ertcdieopoecjddamgkx"
password = "Kamloops@923116"
port = "5432"

[env]
STORE_PC = "343939"
